### ISSUE TITLE
[Feedback] Reddit Widget Oauth

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloud-vue-dashboard#36] opened 2020-09-06 00:06 UTC
Nextcloud 20.0.0beta3 does not noticeably access Reddit widget via Oauth.  Hangs at the activation screen after clicking `Accept` and nothing happens.  Tested on latest Firefox 64-bit stable and Chromium 64-bit Stable on Ubuntu 20.04.1
![](CTrNxf3323A/uf/RIbJ8ukPhhQQ5CMKwSzMj86tO7tc)
![image](https://user-images.githubusercontent.com/1787238/92315421-17b59680-ef9a-11ea-8e39-ebb2e277e9a0.png)

Between the two browser attempts, I did receive a confirmation email from Reddit that I have new app access.  Seems only Chromium was able to work.  I then had to manually paste the app secret from the confirmation email into the Dashboard widget.  Now I see this:
![image](https://user-images.githubusercontent.com/1787238/92315476-ebe6e080-ef9a-11ea-833f-11fac31465aa.png)

**Comment by eneiluj** [comment] 2020-09-06 22:19
Hey! There's a repo for this app: https://github.com/eneiluj/integration_reddit . Anyway, we can continue to talk here.

1. Are you using https to connect to your Nextcloud server?
2. Did you see and accept the protocol registration when you loaded the user linked account settings page?

The page is supposed to ask your browser to be able to open Reddit-specific links. Then when you authorize the app on Reddit, it should redirect you to your Nextcloud (and in some cases show a confirmation dialog).

# Firefox

On Firefox it's at the top of the page and looks like that:
![proto](https://user-images.githubusercontent.com/11291457/92335877-95150000-f09b-11ea-99c8-3de189a0b7f9.png)

and then, after having clicked "authorize":
![proto2](https://user-images.githubusercontent.com/11291457/92336142-bc6ccc80-f09d-11ea-92f4-ed9d46612d00.png)

# Chromium

On Chromium:
![proto_4](https://user-images.githubusercontent.com/11291457/92336328-b1b33700-f09f-11ea-8204-3ad91c7987fb.png)


and then, after having clicked "authorize" it redirect you to the linked accounts settings page without asking anything.

I guess bottom line is that the explanations in the settings should be more explicit.

**Comment by sunjam** [comment] 2020-09-07 16:10
> Are you using https to connect to your Nextcloud server?

Negative, I'm running a testing instance without https on arm64.



> Firefox and Chrome

Thanks, I've followed these instructions with same results.  Chrome is responding more easily than Firefox.

> I guess bottom line is that the explanations in the settings should be more explicit.

It would most benefit me to be able to simply clear or discard my settings so I can start over afaik.  I cannot find a way to do this because deleting "Reddit Integration" will not remove the config settings... once I install and re-enable the integration the problem pops up again.

**Comment by eneiluj** [comment] 2020-09-07 16:51
I realize I forgot to tell you: the client secret is not the authentication token. You have to let the redirection handshake automatically give the token to Nextcloud. There is no manual way to do that.

Protocol registration will only work with a HTTPS setup as browsers are refusing to register protocols in HTTP.

> discard my settings so I can start over afaik

On the server side, you can delete everything by emptying the fields in personal and admin (linked account) settings. There is nothing more stored.

Protocol registrations are stored in the browser, not in Nextcloud DB :grin:.

Applications can be removed in Firefox settings, just search for "Applications". In Chromium it's a bit trickier, you can go there: chrome://settings/handlers to manage/remove protocol registrations.

I think there might still be a bug because the screen you (ghost entries) see should not last forever. Let me have a look. I'll try to reproduce it by setting a wrong token like you probably did :wink:.

**Comment by eneiluj** [comment] 2020-09-07 17:06
I found the bug. It's now solved and will be included in next `integration_reddit` release. It was really not related with your authentication problem.

I'll hide the OAuth button when HTTP is used.

Could you post further issues in https://github.com/eneiluj/integration_reddit ?

Thanks again for the bug report.

**Closed by eneiluj** 2020-09-07 17:06 UTC

**Comment by sunjam** [comment] 2020-09-07 17:07
> I'll hide the OAuth button when HTTP is used.

Fyi, I was able to get Reddit integration working on http by clearing the browser cache and re-installing the app. :+1: 

Cheers.

**Comment by eneiluj** [comment] 2020-09-07 17:11
Ok so you did it by declaring an OAuth app yourself in Reddit dev settings? This is the only way :grin:. When doing that, the OAuth hadshake can redirect to your HTTP page because you declared it in Reddit. Using the default OAuth Reddit app I made only redirects to a custom protocol and this is why HTTPS is needed.

Could you confirm you did it by declaring an OAuth app in Reddit?
